r = int(input("informe um produto: "))
if(r==1):
    print("sul")
if(r==2):
    print("norte")
if(r==3):
    print("leste")
if(r==4):
    print("oeste")
if(r==5):
    print("nordeste")
if(r==6):
    print("nordeste")
if(r==7):
    print("sudeste")
if(r==8):
    print("sudeste")
if(r==9):
    print("sudeste")
if(r==10):
    print("centro-oeste")
if(r==11):
    print("noroeste")
